### ISSUE TITLE
helper scripte mit mysql anstatt mariadb 

### ISSUE THREAD

**Issue by tobiasfaust** [horchi/vdr-epg-daemon#6]
Hi Horchi,
die ganzen Helperscripte von 3PO unter /scripts laufen nur mit mysql, nicht mit mariadb. 
Ist mir gerade aufgefallen .....
grüsse

**Comment by horchi** [comment]
von den Scripten ist eins von 3PO, das verwende ich nicht.
Die anderen funktionieren hier mit mariadb

**Comment by tobiasfaust** [comment]
im mariadb Dockerfile habe ich folgendes eingebaut, damit gehen jetzt auch die meisten scripte, zb "epgd-dropall"
`ln -s /usr/bin/mariadb /usr/bin/mysql`

**Comment by horchi** [comment]
das hier ist der default bei Ubuntu ohne das man den Link selbst setzen muss:
```
root@gate~> ll /usr/bin/mysql
lrwxrwxrwx 1 root root 7 Nov  2  2022 /usr/bin/mysql -> mariadb
```
