### ISSUE TITLE
Umlaute sind falsch in der DB

### ISSUE THREAD

**Issue by tobiasfaust** [horchi/vdr-epg-daemon#7]
Hi Horchi,

Ich habe das Problem das in der MAriaDB die Umlaute falsch enthalten sind. 
zb. Tabelle events: `Abenteuer Leben tÃ¤glich`
Die epgd DB habe ich mit dem Startscript von dir aufgebaut, die mariadb läuft mit
<pre>
[mysqld]
character-set-server=latin1
</pre>

<pre>
CREATE DATABASE IF NOT EXISTS epg2vdr charset utf8;
[....]
</pre>

Schaue ich über phpmyadmin mir die Tabellen an, so stehen alle als Kollation = "utf8mb3_general_ci" drin.

Sowohl im mariadb-Docker als auch im vdr-epgd Docker sind imho die locales korrekt:
<pre>
root@vdr-epgd:/tmp# locale
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=de_DE.UTF-8
LANGUAGE=
LC_CTYPE="de_DE.UTF-8"
LC_NUMERIC="de_DE.UTF-8"
LC_TIME="de_DE.UTF-8"
LC_COLLATE="de_DE.UTF-8"
LC_MONETARY="de_DE.UTF-8"
LC_MESSAGES="de_DE.UTF-8"
LC_PAPER="de_DE.UTF-8"
LC_NAME="de_DE.UTF-8"
LC_ADDRESS="de_DE.UTF-8"
LC_TELEPHONE="de_DE.UTF-8"
LC_MEASUREMENT="de_DE.UTF-8"
LC_IDENTIFICATION="de_DE.UTF-8"
LC_ALL=
root@vdr-epgd:/tmp#
</pre>

Hast du noch eine zündene Idee wo ich suchen kann?

**Comment by horchi** [comment]
show create table ... zeigt bei mir:
```
...
...
) ENGINE=InnoDB AUTO_INCREMENT=2403 DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci ROW_FORMAT=DYNAMIC |

```

und 
```
MariaDB [epg2vdr]>  SELECT @@character_set_database, @@collation_database;
+--------------------------+----------------------+
| @@character_set_database | @@collation_database |
+--------------------------+----------------------+
| utf8                     | utf8_general_ci      |
+--------------------------+----------------------+
1 row in set (0,000 sec)

```

in der Konfiguration finde ich (ist wohl der default):

```
mariadb.conf.d/50-mysql-clients.cnf
default-character-set = utf8mb4

mariadb.conf.d/50-server.cnf
character-set-server  = utf8mb4

mariadb.conf.d/50-client.cnf
default-character-set = utf8mb4
```
Früher bei MySQL musst das wegen der Indizes immer latin1 sein.

Klappt es denn wenn du am SQL Prompt UTF-8  in ein Feld schreibst, wenn ja liegt es vermutlich an einem Client Setting.
Ist denn alles falsch, also das was aus dem Internet über den epgd kommt als auch das was vom Sender über den VDR/epg2vdr in die Tabelle kommt?

**Comment by tobiasfaust** [comment]
ein "show create table ..." liefert ein
`) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci ROW_FORMAT=DYNAMIC`

Ein `SELECT @@character_set_database, @@collation_database;`

liefert `utf8mb3 utf8mb3_general_ci `

laut deiner REAME muss das character-set-server auf latin1 gestellt sein, ich stelle es mal um ....

wenn ich den epgd im docker starte rauschen schon falsche Umlaute durch:
<pre>
[services.d] starting services
[services.d] done.
14:54:01,486  Set locale to 'C'
14:54:01,486  Calling sd_notify(READY=1$STATUS=Ready$MAINPID=123$)
14:54:01,486  Info: Systemd watchdog not configured, epgd won't be sending keep-alive messages!
14:54:01,486  Loading uuid from '/epgd/config/uuid' succeeded [079634EE-622D-4700-864F-44CE6197A035]
14:54:01,496  Starting epgd
14:54:01,496  Initialize python script '/epgd/config/recording.py'
14:54:01,549  Loading plugin: /usr/local/lib/epgd/plugins/libepgd-epgdata.so
14:54:01,550  Loading plugin: /usr/local/lib/epgd/plugins/libepgd-tvsp.so
14:54:01,552  Loading plugin: /usr/local/lib/epgd/plugins/libepgd-tvm.so
14:54:01,555  Read 22 option from /epgd/config/epgd.conf
14:54:01,555  Info: Calling mysql_library_init()
14:54:01,572  Calling mysql_init(123)
14:54:01,576  SQL client character now 'latin1'
14:54:01,577  Checking database connection ...
14:54:01,577  Checking table structure and indices ...
[.....]
Set scraping language to 'en'
[...]
14:26:15,935  lookup 75682/4/21 'Requiem f�r eine Requisite'
14:26:15,952  lookup 75682/4/22 'Der Doppeltod des Dahingegangenen'
14:26:15,968  lookup 75682/4/23 'M�dchenkopf mit Maske'
</pre>

**Comment by horchi** [comment]
dann versuche es mal mit den Einstellungen wer bei mir, scheint ja alles drei anders zu sein.

> Früher bei MySQL musst das wegen der Indizes immer latin1 sein.

scheint inzw. bei mariaDb kein Thema mehr zu sein.

**Comment by horchi** [comment]
hast du das beim start des epgd in seinem log?

```
Nov 22 16:27:29 gate epgd: Set locale to 'de_DE.UTF-8'
Nov 22 16:27:29 gate epgd: SQL client character now 'utf8'

```

**Comment by horchi** [comment]
und das vom vdr/epg2vdr (auch beim Start)

```
16:29:16,root@gate~> grep -i utf /var/log/vdr.log
Nov 22 16:29:15 gate vdr: [384276] codeset is 'UTF-8' - known
Nov 22 16:29:16 gate vdr: epg2vdr: Set locale to 'de_DE.UTF-8'
Nov 22 16:29:16 gate vdr: epg2vdr: detected UTF-8
Nov 22 16:29:16 gate vdr: epg2vdr: SQL client character now 'utf8'

```

**Comment by tobiasfaust** [comment]
Dank deiner Hinweise hab ichs jetzt. Ins Dockerfile muss folgendes rein:
<pre>
RUN sed -i 's/# de_DE.UTF-8 UTF-8/de_DE.UTF-8 UTF-8/g' /etc/locale.gen && \
    locale-gen && \
    update-locale LANG=de_DE.UTF-8 LC_MESSAGES=de_DE.UTF-8 LANGUAGE=de_DE.UTF-8 && \
    sed -i 's/LC_ALL="C"/LC_ALL=de_DE.UTF-8/g' /etc/environment && \
    echo "LANG=de_DE.UTF-8" >> /etc/environment && \
    echo "LC_ALL=de_DE.UTF-8" >> /etc/environment
</pre>

damit rauschen jetzt auf der Konsole auch saubere Umlaute durch :)
