### ISSUE TITLE
Crashes at startup with Python > 3.12

### ISSUE THREAD

**Issue by theonlychriss** [horchi/vdr-epg-daemon#8]
There's Py_Initialize() called (more than once) before calling PyImport_AppendInittab() which seems to be a no-go with Python > 3.12.

Roughly here:
https://github.com/horchi/vdr-epg-daemon/blob/fad192731065ed692ec1b3dd53a9db9a70497083/lib/python.c#L215

This has been solved (at least for me) in this thread of the vdr-portal:
https://www.vdr-portal.de/forum/index.php?thread/136244-epghttpd-mit-problemen-beim-start-kubuntu-24-04/&postID=1370490#post1370490

Thanks in advance for including a solution in one of the next commits or releases.

**Comment by horchi** [comment]
fixed
